command: [
  "sh",
  "-c",
  "flask --app app.py run --host 0.0.0.0 --port ${PORT:-8080}"
]

env:
  # Delta table configuration
  - name: DELTA_TABLE_NAME
    value: "eliao.nifi_to_databricks.nifi_flows"

  # SQL Warehouse connection (for Delta table access via SQL Connector)
  # Note: DATABRICKS_HOST, DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET are automatically provided by Databricks Apps
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/6197de40f3098d2b"

  # Agent notebook path
  - name: AGENT_NOTEBOOK_PATH
    value: "/Workspace/Users/eliao@bpcs.com/agentic_nifi_to_databricks/notebooks/nifi_conversion_dummy_agent"
