command: [
  "sh",
  "-c",
  "flask --app app.py run --host 0.0.0.0 --port ${PORT:-8080}"
]

env:
  # Dynamic job creation - no pre-configured job ID needed
  - name: DELTA_TABLE_NAME
    value: "main.default.nifi_flows"
  - name: AGENT_NOTEBOOK_PATH
    value: "/Workspace/Shared/nifi_conversion_dummy_agent"  # IMPORTANT: Upload notebooks/nifi_conversion_dummy_agent.py to this path in Databricks Workspace
